development:
  adapter: postgresql
  database: datagrid_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: datagrid_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: datagrid_production
  pool: 5
  timeout: 5000
