development:
  clients:
    default:
      database: mongoid
      hosts:
        - localhost:27017
production:
  clients:
    default:
      uri: <%= ENV.fetch("ORMONGO_RS_URL") %>
      database: 'datagrid_demo_production'
      user: 'datagrid_demo_production'
      password: <%= ENV.fetch('ORMONGO_PASSWORD') %>
