development:
  sessions:
    default:
      database: pdb_development
      hosts:
        - localhost:27017
production:
  uri: <%= ENV['MONGOHQ_URL'] %>

  #sessions:
    #default:
      #hosts:
        #- ds029187.mongolab.com:29187
      #database: datagrid_demo
      #username: datagrid
      #password: catastrophe
