development:
  sessions:
    default:
      database: pdb_development
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      database: datagrid_demo
      hosts:
        - ds029187.mongolab.com:29187
      user: datagrid
      password: catastrophe
